language: c
os: linux
script:
    - "make -f camlann_CI.mk clean"
    - "make -f camlann_CI.mk"
    - "./check_style.sh"
addons:
    apt:
        packages:
            - "libsdl2-dev"
            - "libsdl2-ttf-dev"
